# Generated by Django 6.0.3 on 2026-05-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
    ]
