# Generated by Django 6.0.3 on 2026-07-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_club_address_remove_club_city_and_more'),
        ('partners', '0003_partner_logo_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order', 'name', 'id']},
        ),
        migrations.AlterField(
            model_name='partner',
            name='tier',
            field=models.CharField(blank=True, choices=[('general', 'Generálny partner'), ('main', 'Hlavný partner'), ('partner', 'Partner'), ('media', 'Mediálny partner')], default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['club', 'tier', 'order'], name='partners_pa_club_id_92233d_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['club', 'is_active'], name='partners_pa_club_id_2ab019_idx'),
        ),
    ]
