version: "3.9"

services:
  backend:
    build:
      context: .
    container_name: ludimus_backend
    env_file:
      - .env
    environment:
      GUNICORN_WORKERS: ${GUNICORN_WORKERS:-3}
      GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT:-60}
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    restart: always
