version: "3.9"

services:
  backend:
    build:
      context: .
    container_name: ludimus_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    restart: always
