# Generated by Django 6.0.3 on 2026-03-21 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('latest_posts', 'Latest posts'), ('matches', 'Matches'), ('partners', 'Partners'), ('gallery', 'Gallery'), ('cta', 'CTA'), ('custom_html', 'Custom HTML')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_sections', to='clubs.club')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
