# Generated by Django 6.0.3 on 2026-06-21 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='address',
        ),
        migrations.RemoveField(
            model_name='club',
            name='city',
        ),
        migrations.RemoveField(
            model_name='club',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='club',
            name='email',
        ),
        migrations.RemoveField(
            model_name='club',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='club',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='club',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='club',
            name='website_url',
        ),
        migrations.RemoveField(
            model_name='club',
            name='youtube_url',
        ),
    ]
