# Generated by Django 6.0.3 on 2026-04-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_full_name', models.CharField(max_length=255)),
                ('birth_year', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Náborový formulár',
                'verbose_name_plural': 'Náborové formuláre',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Guli',
        ),
    ]
