# Generated by Django 6.0.3 on 2026-04-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guli', '0002_recruitmentform_delete_guli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentform',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
