# Generated by Django 6.0.3 on 2026-06-21 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_club_address_remove_club_city_and_more'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('top_posts', 'Najdôležitejšie novinky'), ('posts', 'Články / novinky'), ('matches_overview', 'Zápasy + tabuľka'), ('next_match', 'Najbližší zápas'), ('recent_matches', 'Posledné zápasy'), ('standings', 'Tabuľka'), ('partners', 'Partneri'), ('poll', 'Anketa'), ('recruitment', 'Nábor'), ('links', 'Klubové odkazy'), ('contact', 'Kontakt'), ('documents', 'Dokumenty'), ('gallery', 'Galéria'), ('achievements', 'Úspechy'), ('custom_text', 'Vlastný text')], max_length=50)),
                ('pre_title', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('subtitle', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('hide_when_empty', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Sekcia stránky',
                'verbose_name_plural': 'Sekcie stránok',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['navigation_order', 'title']},
        ),
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.RemoveField(
            model_name='page',
            name='menu_order',
        ),
        migrations.RemoveField(
            model_name='page',
            name='show_in_menu',
        ),
        migrations.AddField(
            model_name='page',
            name='is_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='menu_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='page',
            name='navigation_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/og/'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('standard', 'Štandardná stránka'), ('home', 'Domovská stránka'), ('about', 'O klube'), ('contact', 'Kontakt'), ('recruitment', 'Nábor'), ('category', 'Kategória'), ('articles', 'Články'), ('custom', 'Vlastná stránka')], default='standard', max_length=30),
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_footer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(condition=models.Q(('is_homepage', True)), fields=('club',), name='unique_homepage_per_club'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page'),
        ),
    ]
