# Generated by Django 6.0.3 on 2026-06-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pagesection_alter_page_options_remove_page_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesection',
            name='subtitle',
        ),
    ]
