# Generated by Django 6.0.3 on 2026-06-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_pagesection_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('top_posts', 'Najdôležitejšie novinky'), ('posts', 'Články / novinky'), ('matches_overview', 'Zápasy + tabuľka'), ('next_match', 'Najbližší zápas'), ('recent_matches', 'Posledné zápasy'), ('standings', 'Tabuľka'), ('partners', 'Partneri'), ('poll', 'Anketa'), ('recruitment', 'Nábor'), ('links', 'Klubové odkazy'), ('contact', 'Kontakt'), ('documents', 'Dokumenty'), ('gallery', 'Galéria'), ('achievements', 'Úspechy'), ('custom_text', 'Vlastný text'), ('about_overview', 'Prehľad o klube s mapou'), ('about_text', 'Textová sekcia o klube'), ('famous_players', 'Známi hráči / odchovanci')], max_length=50),
        ),
    ]
