# Generated by Django 6.0.3 on 2026-06-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_pagesection_image_pagesectionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('top_posts', 'Najdôležitejšie novinky'), ('posts', 'Články / novinky'), ('matches_overview', 'Zápasy + tabuľka'), ('next_match', 'Najbližší zápas'), ('recent_matches', 'Posledné zápasy'), ('standings', 'Tabuľka'), ('leaders', 'Lídri sezóny'), ('partners', 'Partneri'), ('poll', 'Anketa'), ('recruitment', 'Nábor'), ('benefits', 'Benefity'), ('team_categories', 'Kategórie tímov'), ('faq', 'Časté otázky'), ('trainings', 'Tréningy'), ('links', 'Klubové odkazy'), ('custom_links', 'Vlastné odkazy'), ('contact', 'Kontakt'), ('documents', 'Dokumenty'), ('gallery', 'Galéria'), ('achievements', 'Úspechy'), ('custom_text', 'Vlastný text'), ('about_overview', 'Prehľad o klube s mapou'), ('about_text', 'Textová sekcia o klube'), ('famous_players', 'Známi hráči / odchovanci')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='url',
            field=models.CharField(blank=True, help_text='Staršie pole pre jednoduchý odkaz. Pre nové vlastné odkazy použi položky sekcie. Môže byť externá URL alebo interná cesta, napr. /kontakt.', max_length=500),
        ),
    ]
