# Generated by Django 6.0.3 on 2026-06-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_pagesection_section_type_alter_pagesection_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Voliteľné nastavenia vo formáte JSON. Pre klubové dokumenty napr. {"document_ids": [1, 2, 3]}. Pre klubové odkazy napr. {"link_ids": [1, 4, 7]}. Pre vlastné dokumenty a vlastné odkazy používaj položky sekcie.'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='content',
            field=models.TextField(blank=True, help_text='Obsah pre textové sekcie, napr. Vlastný text.'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='file',
            field=models.FileField(blank=True, help_text='Staršie pole pre jeden súbor. Pre viac vlastných dokumentov používaj položky sekcie.', null=True, upload_to='pages/sections/'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='image',
            field=models.ImageField(blank=True, help_text='Voliteľný obrázok/banner najmä pre Hero sekciu.', null=True, upload_to='pages/sections/images/'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('top_posts', 'Najdôležitejšie novinky'), ('posts', 'Články / novinky'), ('matches_overview', 'Zápasy + tabuľka'), ('next_match', 'Najbližší zápas'), ('recent_matches', 'Posledné zápasy'), ('standings', 'Tabuľka'), ('leaders', 'Lídri sezóny'), ('partners', 'Partneri'), ('poll', 'Anketa'), ('recruitment', 'Nábor'), ('benefits', 'Benefity'), ('team_categories', 'Kategórie tímov'), ('faq', 'Časté otázky'), ('trainings', 'Tréningy'), ('links', 'Klubové odkazy'), ('custom_links', 'Vlastné odkazy'), ('contact', 'Kontakt'), ('documents', 'Klubové dokumenty'), ('custom_documents', 'Vlastné dokumenty'), ('gallery', 'Galéria'), ('achievements', 'Úspechy'), ('custom_text', 'Vlastný text'), ('about_overview', 'Prehľad o klube s mapou'), ('about_text', 'Textová sekcia o klube'), ('famous_players', 'Známi hráči / odchovanci')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='url',
            field=models.CharField(blank=True, help_text='Staršie pole pre jednoduchý odkaz. Pre viac vlastných odkazov používaj položky sekcie.', max_length=500),
        ),
        migrations.AlterField(
            model_name='pagesectionitem',
            name='file',
            field=models.FileField(blank=True, help_text='Používa sa pri sekcii Vlastné dokumenty.', null=True, upload_to='pages/sections/items/'),
        ),
    ]
