# Generated by Django 6.0.3 on 2026-06-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_pagesection_config_alter_pagesection_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('home', 'Domov'), ('about', 'O klube'), ('contact', 'Kontakt'), ('recruitment', 'Nábor / Pridaj sa'), ('category', 'Kategória tímu'), ('team_category', 'Kategória tímu'), ('articles', 'Články'), ('custom', 'Vlastná stránka'), ('standard', 'Štandardná stránka')], default='standard', max_length=30),
        ),
    ]
