# Generated by Django 6.0.3 on 2026-06-29 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_page_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSectionContactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_type', models.CharField(choices=[('phone', 'Telefón'), ('email', 'Email'), ('iban', 'IBAN'), ('address', 'Adresa'), ('person', 'Osoba / kontaktná osoba'), ('web', 'Web / URL'), ('text', 'Text / poznámka')], default='text', max_length=30)),
                ('value', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(limit_choices_to={'section_type': 'contact'}, on_delete=django.db.models.deletion.CASCADE, related_name='contact_items', to='pages.pagesection')),
            ],
            options={
                'verbose_name': 'Kontaktná položka sekcie',
                'verbose_name_plural': 'Kontaktné položky',
                'ordering': ['order', 'id'],
            },
        ),
    ]
