# Generated by Django 6.0.3 on 2026-06-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_page_team_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesectioncontactitem',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Popis položky, napr. Telefón, Email, IBAN alebo Adresa.', max_length=120),
        ),
    ]
