# Generated by Django 6.0.3 on 2026-04-17 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('teams', '0002_remove_teammember_team_remove_teammember_club_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.CharField(max_length=20)),
                ('oldest_birth_year_offset', models.PositiveIntegerField()),
                ('youngest_birth_year_offset', models.PositiveIntegerField()),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_season', to='clubs.club')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
