# Generated by Django 6.0.3 on 2026-04-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_clubseason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubseason',
            name='oldest_birth_year_offset',
        ),
        migrations.RemoveField(
            model_name='clubseason',
            name='youngest_birth_year_offset',
        ),
    ]
