# Generated by Django 6.0.3 on 2026-04-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_clubseason_oldest_birth_year_offset_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubseason',
            options={'ordering': ['club__name']},
        ),
        migrations.AddField(
            model_name='category',
            name='oldest_birth_year_offset',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='youngest_birth_year_offset',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
