# Generated by Django 6.0.3 on 2026-04-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_clubseason_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='oldest_birth_year_offset',
        ),
        migrations.RemoveField(
            model_name='category',
            name='youngest_birth_year_offset',
        ),
    ]
