# Generated by Django 6.0.3 on 2026-04-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_category_oldest_birth_year_offset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='coach_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='category',
            name='coach_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='category',
            name='coach_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
