# Generated by Django 6.0.3 on 2026-05-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_category_coach_email_category_coach_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
