# Generated by Django 6.0.3 on 2026-05-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='category',
            name='display_years',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
