# Generated by Django 6.0.3 on 2026-05-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_category_display_code_category_display_years'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='display_code',
        ),
        migrations.RemoveField(
            model_name='category',
            name='display_years',
        ),
        migrations.AddField(
            model_name='category',
            name='category_subname',
            field=models.CharField(blank=True, help_text='Krátky vizuálny názov kategórie, napr. MEX, U19, U17, U11-U9.', max_length=30),
        ),
    ]
