# Generated by Django 6.0.3 on 2026-05-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_alter_category_options_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hlavná fotka kategórie zobrazovaná v hero sekcii na webe.', null=True, upload_to='categories/hero/'),
        ),
        migrations.AddField(
            model_name='category',
            name='league_name',
            field=models.CharField(blank=True, default='', help_text='Názov ligy zobrazovaný na webe, napr. Slovenská florbalová extraliga.', max_length=150),
        ),
    ]
