# Generated by Django 6.0.3 on 2026-07-12 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_szfbautosyncconfig'),
        ('teams', '0011_category_hero_image_category_league_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='szfb_team_watch',
            field=models.ForeignKey(blank=True, help_text='SZFB sledovanie, z ktorého web číta tabuľku, zápasy a štatistiky.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_categories', to='scraper.szfbteamwatch'),
        ),
    ]
