# Generated by Django 6.0.3 on 2026-07-14 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_club_address_remove_club_city_and_more'),
        ('teams', '0012_category_szfb_team_watch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='teams.category')),
            ],
            options={
                'verbose_name': 'Category link',
                'verbose_name_plural': 'Category links',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_locations', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Training location',
                'verbose_name_plural': 'Training locations',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Pondelok'), (2, 'Utorok'), (3, 'Streda'), (4, 'Štvrtok'), (5, 'Piatok'), (6, 'Sobota'), (7, 'Nedeľa')])),
                ('start_time', models.TimeField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='teams.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_trainings', to='teams.traininglocation')),
            ],
            options={
                'verbose_name': 'Category training',
                'verbose_name_plural': 'Category trainings',
                'ordering': ['order', 'weekday', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='traininglocation',
            constraint=models.UniqueConstraint(fields=('club', 'name'), name='unique_training_location_name_per_club'),
        ),
        migrations.AddConstraint(
            model_name='categorytraining',
            constraint=models.UniqueConstraint(fields=('category', 'weekday', 'start_time', 'location'), name='unique_category_training_slot'),
        ),
    ]
