# Generated by Codex on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_polloption_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="polloption",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="polls/videos/",
            ),
        ),
    ]
