# Generated by Django 6.0.3 on 2026-03-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SzfbCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szfb_competition_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('season', models.CharField(blank=True, default='', max_length=50)),
                ('source_url', models.URLField(blank=True, default='')),
                ('standings_url', models.URLField(blank=True, default='')),
                ('results_url', models.URLField(blank=True, default='')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scrapersource',
            name='club',
        ),
        migrations.CreateModel(
            name='SzfbStandingRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('team_name', models.CharField(max_length=255)),
                ('played', models.PositiveIntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='scraper.szfbcompetition')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('competition', 'position')},
            },
        ),
        migrations.CreateModel(
            name='SzfbTeamWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('team_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_teams', to='scraper.szfbcompetition')),
            ],
        ),
        migrations.CreateModel(
            name='SzfbMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('finished', 'Finished'), ('upcoming', 'Upcoming')], max_length=20)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('match_time', models.TimeField(blank=True, null=True)),
                ('opponent', models.CharField(max_length=255)),
                ('venue', models.CharField(blank=True, default='', max_length=255)),
                ('result', models.CharField(blank=True, default='', max_length=30)),
                ('is_home', models.BooleanField(blank=True, null=True)),
                ('external_key', models.CharField(max_length=255, unique=True)),
                ('watched_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='scraper.szfbteamwatch')),
            ],
            options={
                'ordering': ['match_date', 'match_time'],
            },
        ),
        migrations.DeleteModel(
            name='ScraperJob',
        ),
        migrations.DeleteModel(
            name='ScraperSource',
        ),
    ]
