# Generated by Django 6.0.3 on 2026-05-06 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_szfbcompetition_remove_scrapersource_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='szfbteamwatch',
            name='competitor_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SzfbPlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('player_name', models.CharField(max_length=255)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('team_short_name', models.CharField(blank=True, default='', max_length=50)),
                ('player_position', models.CharField(blank=True, default='', max_length=20)),
                ('games', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('points_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('esp', models.PositiveIntegerField(default=0)),
                ('ppp', models.PositiveIntegerField(default=0)),
                ('shp', models.PositiveIntegerField(default=0)),
                ('pim', models.PositiveIntegerField(default=0)),
                ('watched_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='scraper.szfbteamwatch')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('watched_team', 'rank', 'player_name')},
            },
        ),
    ]
