# Generated by Django 6.0.3 on 2026-06-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_szfbteamwatch_competitor_id_szfbplayerstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='szfbplayerstat',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='szfbplayerstat',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='szfbplayerstat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='szfbplayerstat',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='szfbplayerstat',
            name='jersey_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='szfbplayerstat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/photos/'),
        ),
    ]
