# Generated by Django 6.0.3 on 2026-07-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_szfbplayerstat_bio_szfbplayerstat_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='szfbcompetition',
            name='sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='szfbcompetition',
            name='sync_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='szfbcompetition',
            name='sync_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='szfbcompetition',
            name='sync_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='szfbcompetition',
            name='sync_status',
            field=models.CharField(choices=[('idle', 'Neaktívne'), ('running', 'Prebieha'), ('success', 'Hotovo'), ('error', 'Chyba')], default='idle', max_length=20),
        ),
    ]
