# Generated by Django 6.0.3 on 2026-07-03 17:53

import django.db.models.deletion
from django.db import migrations, models


def backfill_atu_kosice_team_watches(apps, schema_editor):
    Club = apps.get_model("clubs", "Club")
    SzfbTeamWatch = apps.get_model("scraper", "SzfbTeamWatch")

    club = Club.objects.filter(slug="atu-kosice").first()

    if not club:
        return

    SzfbTeamWatch.objects.filter(club__isnull=True).update(club=club)


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_club_address_remove_club_city_and_more'),
        ('scraper', '0005_szfbcompetition_sync_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='szfbteamwatch',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='szfb_team_watches', to='clubs.club'),
        ),
        migrations.RunPython(
            backfill_atu_kosice_team_watches,
            migrations.RunPython.noop,
        ),
    ]
