# Generated by Django 6.0.3 on 2026-07-03 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_club_address_remove_club_city_and_more'),
        ('scraper', '0006_szfbteamwatch_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('identity_key', models.CharField(db_index=True, max_length=320)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/photos/')),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, default='', max_length=50)),
                ('bio', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_players', to='clubs.club')),
            ],
            options={
                'ordering': ['display_order', 'full_name'],
            },
        ),
        migrations.AddField(
            model_name='szfbplayerstat',
            name='club_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='szfb_stats', to='scraper.clubplayer'),
        ),
        migrations.AddConstraint(
            model_name='clubplayer',
            constraint=models.UniqueConstraint(fields=('club', 'identity_key'), name='unique_club_player_identity'),
        ),
    ]
