# Generated by Django 6.0.3 on 2026-07-06 09:17

import apps.scraper.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_club_address_remove_club_city_and_more'),
        ('scraper', '0007_clubplayer_szfbplayerstat_club_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SzfbAutoSyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('daily', 'Každý deň'), ('weekly', 'Každý týždeň')], default='weekly', max_length=20)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Pondelok'), (1, 'Utorok'), (2, 'Streda'), (3, 'Štvrtok'), (4, 'Piatok'), (5, 'Sobota'), (6, 'Nedeľa')], default=0)),
                ('run_time', models.TimeField(default=apps.scraper.models.default_auto_sync_time)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('idle', 'Neaktívne'), ('success', 'Hotovo'), ('error', 'Chyba'), ('skipped', 'Preskočené')], default='idle', max_length=20)),
                ('last_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='szfb_auto_sync_config', to='clubs.club')),
            ],
            options={
                'verbose_name': 'SZFB automatická synchronizácia',
                'verbose_name_plural': 'SZFB automatické synchronizácie',
            },
        ),
    ]
