# Generated by Django 6.0.3 on 2026-09-07 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_club_address_remove_club_city_and_more'),
        ('scraper', '0009_alter_szfbstandingrow_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SzfbMatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_identity', models.CharField(db_index=True, max_length=255)),
                ('team_label', models.CharField(blank=True, default='', max_length=255)),
                ('team_name', models.CharField(blank=True, default='', max_length=255)),
                ('competitor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('szfb_competition_id', models.PositiveIntegerField(blank=True, null=True)),
                ('competition_name', models.CharField(blank=True, default='', max_length=255)),
                ('competition_season', models.CharField(blank=True, default='', max_length=50)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField(blank=True, null=True)),
                ('opponent', models.CharField(max_length=255)),
                ('venue', models.CharField(blank=True, default='', max_length=255)),
                ('result', models.CharField(max_length=30)),
                ('is_home', models.BooleanField(blank=True, null=True)),
                ('external_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='szfb_match_history', to='clubs.club')),
            ],
            options={
                'ordering': ['-match_date', '-match_time', '-id'],
                'constraints': [models.UniqueConstraint(fields=('club', 'team_identity', 'external_key'), name='unique_szfb_match_history_entry')],
            },
        ),
    ]
