# Generated by Django 6.0.3 on 2026-09-13 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_szfbmatchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SzfbGoalieStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szfb_player_id', models.PositiveIntegerField(db_index=True)),
                ('rank', models.PositiveIntegerField()),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('player_name', models.CharField(max_length=255)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('games', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('overtime_wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('overtime_losses', models.PositiveIntegerField(default=0)),
                ('shots_against', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('goals_against_average', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('save_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('minutes_played_seconds', models.PositiveIntegerField(default=0)),
                ('shutouts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['rank', 'player_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='szfbplayerstat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='szfbplayerstat',
            name='szfb_player_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='szfbplayerstat',
            constraint=models.UniqueConstraint(fields=('watched_team', 'szfb_player_id'), name='unique_szfb_player_stat_per_team'),
        ),
        migrations.AddField(
            model_name='szfbgoaliestat',
            name='club_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='szfb_goalie_stats', to='scraper.clubplayer'),
        ),
        migrations.AddField(
            model_name='szfbgoaliestat',
            name='watched_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goalie_stats', to='scraper.szfbteamwatch'),
        ),
        migrations.AddConstraint(
            model_name='szfbgoaliestat',
            constraint=models.UniqueConstraint(fields=('watched_team', 'szfb_player_id'), name='unique_szfb_goalie_stat_per_team'),
        ),
    ]
