# Generated by Django 6.0.3 on 2026-09-13 13:51

import apps.scraper.models
import django.db.models.deletion
from django.db import migrations, models


def copy_club_configs_to_watches(apps, schema_editor):
    OldConfig = apps.get_model("scraper", "SzfbAutoSyncConfig")
    WatchConfig = apps.get_model("scraper", "SzfbWatchAutoSyncConfig")
    TeamWatch = apps.get_model("scraper", "SzfbTeamWatch")

    for old_config in OldConfig.objects.all().iterator():
        for watch in TeamWatch.objects.filter(club_id=old_config.club_id).iterator():
            WatchConfig.objects.create(
                watch_id=watch.id,
                is_enabled=old_config.is_enabled and watch.is_active,
                frequency=old_config.frequency,
                weekday=old_config.weekday,
                run_time=old_config.run_time,
                last_run_at=old_config.last_run_at,
                next_run_at=old_config.next_run_at,
                last_status=old_config.last_status,
                last_message=old_config.last_message,
            )


def copy_watch_configs_back_to_clubs(apps, schema_editor):
    OldConfig = apps.get_model("scraper", "SzfbAutoSyncConfig")
    WatchConfig = apps.get_model("scraper", "SzfbWatchAutoSyncConfig")

    seen_club_ids = set()
    configs = WatchConfig.objects.select_related("watch").order_by("id")
    for watch_config in configs.iterator():
        club_id = watch_config.watch.club_id
        if not club_id or club_id in seen_club_ids:
            continue
        seen_club_ids.add(club_id)
        OldConfig.objects.create(
            club_id=club_id,
            is_enabled=watch_config.is_enabled,
            frequency=watch_config.frequency,
            weekday=watch_config.weekday,
            run_time=watch_config.run_time,
            last_run_at=watch_config.last_run_at,
            next_run_at=watch_config.next_run_at,
            last_status=watch_config.last_status,
            last_message=watch_config.last_message,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_szfbgoaliestat_alter_szfbplayerstat_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SzfbWatchAutoSyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('daily', 'Každý deň'), ('weekly', 'Každý týždeň')], default='weekly', max_length=20)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Pondelok'), (1, 'Utorok'), (2, 'Streda'), (3, 'Štvrtok'), (4, 'Piatok'), (5, 'Sobota'), (6, 'Nedeľa')], default=0)),
                ('run_time', models.TimeField(default=apps.scraper.models.default_auto_sync_time)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('idle', 'Neaktívne'), ('success', 'Hotovo'), ('error', 'Chyba'), ('skipped', 'Preskočené')], default='idle', max_length=20)),
                ('last_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_sync_config', to='scraper.szfbteamwatch')),
            ],
            options={
                'verbose_name': 'SZFB automatická synchronizácia tímu',
                'verbose_name_plural': 'SZFB automatické synchronizácie tímov',
            },
        ),
        migrations.RunPython(
            copy_club_configs_to_watches,
            copy_watch_configs_back_to_clubs,
        ),
        migrations.DeleteModel(
            name='SzfbAutoSyncConfig',
        ),
    ]
