# Generated by Django 6.0.3 on 2026-06-17 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='Kontakt', max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('address', models.CharField(max_length=255)),
                ('chairman_name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=80)),
                ('iban', models.CharField(blank=True, max_length=80)),
                ('map_label', models.CharField(max_length=160)),
                ('map_address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Kontaktné informácie',
                'verbose_name_plural': 'Kontaktné informácie',
            },
        ),
    ]
