# Generated by Django 6.0.3 on 2026-06-17 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_info', '0002_alter_contactinfo_latitude_and_more'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to='club_documents/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Klubový dokument',
                'verbose_name_plural': 'Klubové dokumenty',
                'ordering': ['order', 'title'],
            },
        ),
    ]
