# Generated by Django 6.0.3 on 2026-06-21 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_info', '0003_clubdocument'),
        ('clubs', '0002_remove_club_address_remove_club_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon_type', models.CharField(blank=True, default='', help_text='Ak necháš prázdne, typ ikonky sa automaticky určí podľa URL.', max_length=40)),
                ('logo', models.FileField(blank=True, null=True, upload_to='clubs/links/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Klubový odkaz',
                'verbose_name_plural': 'Klubové odkazy',
                'ordering': ['order', 'title'],
            },
        ),
    ]
