# Generated by Django 6.0.3 on 2026-07-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_info', '0004_clublink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='section_label',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='title',
        ),
    ]
