# Generated by Django 6.0.3 on 2026-03-21 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opponent', models.CharField(max_length=255)),
                ('competition', models.CharField(blank=True, max_length=255)),
                ('round_label', models.CharField(blank=True, max_length=100)),
                ('match_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_home', models.BooleanField(default=True)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('external_source', models.CharField(blank=True, max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='clubs.club')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='teams.team')),
            ],
            options={
                'ordering': ['-match_date'],
            },
        ),
    ]
