# Generated by Django 6.0.3 on 2026-04-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team',
        ),
    ]
