# Generated by Django 6.0.3 on 2026-04-17 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_remove_match_team'),
        ('teams', '0002_remove_teammember_team_remove_teammember_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='teams.category'),
        ),
    ]
